-   id: prefix_and_issue_num
    name: prefix_and_issue_num
    description: Get issue number from branch name and add to commit message.
    entry: prefix_and_issue_num
    language: python
    stages: [commit-msg]